### ISSUE TITLE
Design review agenda carrousel

### ISSUE THREAD

**Issue by SamaraFellaDina** [Nazneen05x/S4-S19-Bieb-In-Bloei#28]
# Kijken naar de verschillende ontwerpen

## eerste ontwerp
![image](https://github.com/user-attachments/assets/7073db6e-9d78-40ba-8fe2-eee29c345c1b)
* erg duidelijk
* Misschien de knop centreren? dit staat eigenlijk ook al goed.
* Misschien in plaats van 'meld je aan', 'aanmelden' gebruiken? 
* in plaats van zaterdag 1 oktober 2023, kan je misschien beter gebruiken 01/12/23, dan kunnen mensen zelf de datum checken. Staat misschien wat overzichtelijker
  * je kan deze tekst dan ook wat dikker maken, of juist het onderwerp. Het is net waarop je de aandacht wilt vestigen. Je zou dan beter het onderwerp dikker kunnen maken en de datum wat dunner om mensen sneller geinteresseert te maken

## tweede ontwerp
![image](https://github.com/user-attachments/assets/8c394346-ba0f-4ae5-b400-1c3a653988be)
* Ik denk dat dit misschien te onduidelijk is en dat de gebruiker meer gaat focussen op de afbeelding dan op de daadwerkelijke data
* borders zijn overgins wel leuk, misschien leuk om te kijken wat voor soort border hoort bij de huisstijl en daarop alles laten aansluiten

## derde ontwerp
![image](https://github.com/user-attachments/assets/8e977fa4-9633-48f2-acde-2c8dadb241fb)
* dit ontwerp lijkt op het eerste ontwerp
* naar mijn mening vind ik de eerste leuker, dit lijkt een beetje op een televisie 📺.

# Algemeen 
* ik zie de informatie knop, maar deze ziet er een beetje gekkig uit met het `i` knopje. Ik zou kijken of je of 'informatie' gebruikt, of de `i` knop, of een combinatie van beide.
* navigatie knoppen zijn nice
* het contrast is duidelijk.

# conclusie
Ik vind het eerste ontwerp het beste werken
* het is duidelijk 
* en prikkelt niet te veel
* de gebruiker gaat waarschijnlijk sneller op het onderwerp letten (misschien een user test doen en kijken wat mensen doen).
* Wanneer je hiermee door wilt gaan, zou ik even naar mijn feedback kijken over het ontwerp om het net wat netter op te maken 

Lekker bezig!

![](https://media.giphy.com/media/CLQNFY6YIHanjWSEhW/giphy.gif?cid=82a1493bany27kspm4do3zj4ua3vlkzo5oo1rsfchrqrefll&ep=v1_gifs_trending&rid=giphy.gif&ct=g)

**Comment by Nazneen05x** [comment]
@SamaraFellaDina  Wow bedankt voor je uitgebreide feedback, ik ga het verwerken thanks! 
![image](https://github.com/user-attachments/assets/74477a10-2741-4c79-b191-e58e7ceb0347)

**Comment by Nazneen05x** [comment]
@SamaraFellaDina Ik heb het ontwerp aangepast! Vind het nu veel cleaner! Thanks!!  
<img width="1194" alt="Scherm­afbeelding 2024-09-18 om 09 45 33" src="https://github.com/user-attachments/assets/078259e4-89ae-4a11-a293-319feab25f17">
